---
AWSTemplateFormatVersion: '2010-09-09'
Description: project de la team AWS_A_B_I_Q
Resources:
  EC2:
    Type: AWS::EC2::Instance
    DeletionPolicy: Retain
    Properties: 
      ImageId: "ami-0c5599c53178a7d77"
  VPC:
    Type: AWS::EC2::VPC
    DeletionPolicy: Retain
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsHostnames: True
      EnableDnsSupport: True
  Subnet:
    Type: AWS::EC2::Subnet
    DeletionPolicy: Retain
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: "us-west-1"    
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DeletionPolicy: Retain
    DependsOn: VPC
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    DeletionPolicy: Retain
    Properties:
      VpcId: !Ref VPC
  SecGrp:
    Type: AWS::EC2::SecurityGroup
    DeletionPolicy: Retain
    Properties: 
      GroupDescription: "allow SSH & HTTP & HTTPS"
      VpcId: !Ref VPC
      GroupName: "SecGrp"
      SecurityGroupIngress:
        - IpProtocol: TCP
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: TCP
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: TCP
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress: 
        - IpProtocol: TCP
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: TCP
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: TCP
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

          